### ISSUE TITLE
Bug: 本地sd是否支持img2img

### ISSUE THREAD

**Issue by yulongyu** [koishijs/novelai-bot#104]
### Describe the bug

本地部署的sd,text2img成功，但是img2img一直失败，无报错信息,qq机器人调用报错500，接口信息如下：

### Steps to reproduce

本地部署

### Expected behavior

支持图生图模式

### Screenshots

![image](https://user-images.githubusercontent.com/36722401/200512982-14713db5-8549-4ba4-9a27-b6f7dba7ae08.png)

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version: 
全部最新版本

**Comment by MirrorCY** [comment]
你尝试在这个界面调用此接口，如果也报错 500 请前往 SD-WebUI 报告 issue

**Comment by yulongyu** [comment]
当我调用这个接口 报错500
![image](https://user-images.githubusercontent.com/36722401/200514711-e3d7cc82-64d8-41f5-8cc6-293c7ecab44a.png)

**Comment by MirrorCY** [comment]
> 当我调用这个接口 报错500

是的，这就说明问题出在那边

**Comment by MaikoTan** [comment]
There should be error messages output from your sd-webui side, did you get anything about it?

应该有错误信息从sd-webui方面输出，你得到任何东西了吗？

**Comment by yulongyu** [comment]
暂时没有有用的信息，有用的我都会复制给你，我在本地部署的webui界面调用，图生图功能是正常的，不明白为嘛接口调用不行，是网络问题么？比如跨域？我不懂网络

**Comment by MirrorCY** [comment]
> 暂时没有有用的信息，有用的我都会复制给你，我在本地部署的webui界面调用，图生图功能是正常的，不明白为嘛接口调用不行，是网络问题么？比如跨域？我不懂网络

不出意外的话，你的 webui console 里应该有至少一条 `IndexError: list index out of range` 报错

**Comment by yulongyu** [comment]
> Well, the img2img feature was implemented in #79 already, although it is still experimental.
> 
> Maybe should I give you a check list so you can trouble shoot on your side.
> 
> 1. Make sure you are using the latest commit of https://github.com/AUTOMATIC1111/stable-diffusion-webui
> 2. Use Python 3.10 (DO NOT use any other versions of Python)
> 3. Make sure the `--api` parameter was passed
> 4. If your bot and webui were deployed on different machines, you should pass `--listen` as well
> 
> 嗯，img2img的功能已经在#79中实现了，尽管它仍然是实验性的。
> 
> 也许我应该给你一个检查清单，这样你就可以在你那边进行故障排除。
> 
> 1. 确保你使用的是 https://github.com/AUTOMATIC1111/stable-diffusion-webui 的最新提交版本
> 2. 使用 Python 3.10 (**不要**使用任何其他版本的 Python)
> 3. 确保`--api`参数已经通过
> 4. 如果你的机器人和webui被部署在不同的机器上，你也应该传递`--listen`。

恩这几点我都检查了，我确实是在另一个机器上，--listen必须加才能访问，我刚才登陆另一台本地访问接口，也报相同错误 Internal Server Error 没有其他有用信息，明天再查一遍

**Comment by yulongyu** [comment]
我在控制台找到一些错误信息@MaikoTan @MirrorCY 
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/yyl/stable-diffusion-webui/modules/api/api.py", line 84, in img2imgapi
    mask = decode_base64_to_image(mask)
  File "/home/yyl/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 45, in decode_base64_to_image
    content = encoding.split(";")[1]
IndexError: list index out of range

**Comment by MaikoTan** [comment]
You are the n-th one I don't know that has this error occurred.
Obviously this is the issue of sd-webui itself, so it cannot be fixed on our side. I would recommend you to report bugs on their side.
What I can do is continuously tracking commits from sd-webui and update if anything broken. Amen.

你是第n个我不知道的人有这个错误发生。
很明显这是sd-webui自身的议题，因此它不能在我们这边修复。我会推荐你在他们方面报告缺陷。
我能做的是继续跟踪来自sd-webui的提交，并且在有东西损坏的时候更新。阿门。

**Comment by MaikoTan** [comment]
Oh, I think it can be fixed on our side.
The patch is on the way, please give it another heure.

噢，我想它可以在我们这边修复。
这个补丁在路上，请给它另一个小时。
