### ISSUE TITLE
Bug: 更新至 1.14.5 后插件无法启用

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/novelai-bot#126]
### Describe the bug

控制台报错 `[W] app Error: Cannot find module './locales/zh-TW'`
插件无法成功加载
help 命令中没有 novelai 命令
novelai 关键词无法触发插件

### Steps to reproduce

将插件从 1.14.2 版本更新至 1.14.5 版本可以触发
将插件从 1.14.5 版本降级至 1.14.2 版本恢复正常

### Expected behavior

可以正常加载 novelai 插件

### Relevant log output

```shell
2022-11-21 07:47:46 [I] app apply plugin gocqhttp
2022-11-21 07:47:46 [I] app apply plugin recall
2022-11-21 07:47:46 [I] app apply plugin novelai
2022-11-21 07:47:46 [I] app apply plugin crazy-thursday
2022-11-21 07:47:46 [W] app Error: Cannot find module './locales/zh-TW'
                        Require stack:
                        - /koishi/node_modules/koishi-plugin-novelai/lib/index.js
                        - /koishi/node_modules/@koishijs/loader/lib/node.js
                        - /koishi/node_modules/@koishijs/cli/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
                            at Module._load (node:internal/modules/cjs/loader:841:27)
                            at Module.require (node:internal/modules/cjs/loader:1061:19)
                            at require (node:internal/modules/cjs/helpers:103:18)
                            at Object.apply (/koishi/node_modules/koishi-plugin-novelai/lib/index.js:45:30)
                            at Runtime.apply (/koishi/node_modules/cordis/lib/index.cjs:371:38)
                            at Runtime.start (/koishi/node_modules/cordis/lib/index.cjs:432:12)
                            at Runtime.restart (/koishi/node_modules/cordis/lib/index.cjs:231:10)
                            at Runtime.setup (/koishi/node_modules/cordis/lib/index.cjs:420:10)
                            at new Runtime (/koishi/node_modules/cordis/lib/index.cjs:389:12)
2022-11-21 07:47:46 [I] app server listening at http://0.0.0.0:5140
2022-11-21 07:47:46 [D] gocqhttp 将使用 device.json 内的设备信息运行Bot. 
2022-11-21 07:47:46 [D] gocqhttp 当前版本:v1.0.0-rc3 
2022-11-21 07:47:46 [D] gocqhttp 开始尝试登录并同步消息... 
2022-11-21 07:47:46 [D] gocqhttp 使用协议: iPad
```

### Launcher

Containers (Docker, Kubernates, etc)

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: ubuntu server 22.04 docker
- Koishi version: 4.10.2

### Additional context

谢谢你，Maiko

**Comment by MaikoTan** [comment]
Already fixed in code. But didn't release.

已经在代码中修复。但是还没有发行。

**Comment by MirrorCY** [comment]
收到  替群友催版中~

**Comment by shigma** [comment]
已修复。没想到是大小写问题……之前文件是 `zh-tw` 改成 `zh-TW` 以后就没法识别了。

**Comment by MirrorCY** [comment]
🚀 加深了对大小写敏感的理解
