### ISSUE TITLE
Bug: QQ群发送指令没反应，但私聊可以

### ISSUE THREAD

**Issue by FXDYJ** [koishijs/novelai-bot#146]
### Describe the bug

如题

### Steps to reproduce

按照教程搞得

### Expected behavior

在群内也可正常调用

### Screenshots

![Snipaste_2022-12-06_14-07-37](https://user-images.githubusercontent.com/81761850/205834500-d70d490d-78d0-4bf1-a571-11aa381bff6f.png)
![Snipaste_2022-12-06_14-08-18](https://user-images.githubusercontent.com/81761850/205834605-f77e1f28-29b1-43d3-ae9c-ade80d33d058.png)
![Snipaste_2022-12-06_14-13-19](https://user-images.githubusercontent.com/81761850/205835490-5e5ff717-0068-401d-a5e0-5ba62b99b656.png)

请简洁明了的把事情完整的说出来。如果你在提问：1.提问前请熟读该项目的README。2.请熟读https://lug.ustc.edu.cn/wiki/doc/smart-questions/
↑这东西是我自动回复↑

### Relevant log output

```shell
文本版日志：
2022-12-06 13:56:39 [D] gocqhttp 收到好友 飞翔到云间(3012287203) 的消息: 约稿 (218469657)
2022-12-06 13:56:39 [D] gocqhttp 发送好友 3012287203(3012287203)  的消息: [{"type":" ... (1300492196)
2022-12-06 13:56:40 [D] gocqhttp 收到好友 飞翔到云间(3012287203) 的消息: 请简洁明了的把事情完整的说出来。如果你在提问：1.提问前请熟读该项目的README。2.请熟读https://lug.ustc.edu.cn/wiki/doc/smart-questions/ (681140532)
2022-12-06 13:56:40 [W] session 请简洁明了的把事情完整的说出来。如果你在提问：1.提问前请熟读该项目的README。2.请熟读https://lug.ustc.edu.cn/wiki/doc/smart-questions/
                        TypeError: items is not iterable
                            at Session.suggest (D:\koishi-desktop-win-x64-v0.8.1\data\instances\default\node_modules\@koishijs\plugin-suggest\lib\index.cjs:83:22)
                            at D:\koishi-desktop-win-x64-v0.8.1\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1677:36
                            at Object.compose (D:\koishi-desktop-win-x64-v0.8.1\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:482:45)
                            at Array.<anonymous> (D:\koishi-desktop-win-x64-v0.8.1\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:708:38)
                            at next (D:\koishi-desktop-win-x64-v0.8.1\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:713:69)
                            at sendNext (D:\koishi-deskt...
2022-12-06 13:56:51 [D] gocqhttp 收到群 [CN]飞翔服务器-2周年周(951358735) 内 飞翔到云间(3012287203) 的消息: 约稿 (-30760778)
2022-12-06 13:56:51 [D] gocqhttp 收到群 [CN]飞翔服务器-2周年周(951358735) 内 AI-bot(3278531245) 的消息: novelai <prompts>
2022-12-06 13:56:51 [I] gocqhttp AI 画图
2022-12-06 13:56:51 [I] gocqhttp 别名：nai。
2022-12-06 13:56:51 [I] gocqhttp 输入用逗号隔开的英文标签，例如 Mr.Quin, dark sword, red eyes。
2022-12-06 13:56:51 [I] gocqhttp 查找标签可以使用 Danbooru。
2022-12-06 13:56:51 [I] gocqhttp 快来给仓库点个 star 吧：https://github.com/koishijs/novelai-bot
2022-12-06 13:56:51 [I] gocqhttp 可用的选项有：
2022-12-06 13:56:51 [I] gocqhttp -r, --resolution <resolution>  设定图片尺寸
2022-12-06 13:56:51 [I] gocqhttp -s, --sampler <sampler>  设置采样器
2022-12-06 13:56:51 [I] gocqhttp -x, --seed <seed>  设置随机种子
2022-12-06 13:56:51 [I] gocqhttp -c, --scale <scale>  设置对输入的服从度
2022-12-06 13:56:51 [I] gocqhttp -u, --undesired <undesired>  排除标签
2022-12-06 13:56:51 [I] gocqhttp 可用的子指令有：
2022-12-06 13:56:51 [I] gocqhttp novelai.upscale  AI 放大图片 (-1993502688
```

### Launcher

Koishi Desktop

### Backend

NAIFU

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version:

**Comment by MaikoTan** [comment]
Unload and remove the suggest plugin, and then reboot your koishi.

卸载并移除建议插件，然后重启你的恋石。

**Comment by FXDYJ** [comment]
> Unload and remove the suggest plugin, and then reboot your koishi.
> 
> 卸载并移除建议插件，然后重启你的恋石。

还是不行

**Comment by MirrorCY** [comment]
检查数据库中 `channel` 表内的 `assignee` 字段，确认里面的账号都是你当前 bot 的 QQ 号。

**Comment by MaikoTan** [comment]
Is There any differents in log after removing the suggest plugin?
Please post your logs.

在移除了建议插件以后那里有什么区别在日志里吗？
请发布你的日志。

**Comment by FXDYJ** [comment]
> 检查数据库中 `channel` 表内的 `assignee` 字段，确认里面的账号都是你当前 bot 的 QQ 号。

栓Q，解决了，账号不对
