### ISSUE TITLE
Bug: 使用风控号约稿会导致 Koishi 卡死，必须手动重启

### ISSUE THREAD

**Issue by pansx** [koishijs/novelai-bot#63]
Koishi/4.9.6,koishi-plugin-gocqhttp3.1.3,ws协议
请求能到达nai,但画完成后没有回复并进入卡死状态,后台虽然有响应但使用chat插件无法向任何人发送消息,无新日志输出
使用的tag:
(((masterpiece))),best quality, illustration,(beautiful detailed girl),beautiful detailed glow,detailed ice,beautiful detailed water,(beautiful detailed eyes),expressionless,beautiful detailed white gloves, (floating palaces:1.3),azure hair,disheveled hair,long bangs, hairs between eyes, (skyblue dress),black ribbon,white bowties,midriff,{{{half closed eyes}}},,big forhead,blank stare,flower,large top sleeves,(((ice crystal texture wings)))

Negative prompt: multiple breasts, (mutated hands and fingers:1.5 ), (long body :1.3), (mutation, poorly drawn :1.2) , black-white, bad anatomy, liquid body, liquid tongue, disfigured, malformed, mutated, anatomical nonsense, text font ui, error, malformed hands, long neck, blurred, lowers, lowres, bad anatomy, bad proportions, bad shadow, uncoordinated body, unnatural body, fused breasts, bad breasts, huge breasts, poorly drawn breasts, extra breasts, liquid breasts, heavy breasts, missing breasts, huge haunch, huge thighs, huge calf, bad hands, fused hand, missing hand, disappearing arms, disappearing thigh, disappearing calf, disappearing legs, fused ears, bad ears, poorly drawn ears, extra ears, liquid ears, heavy ears, missing ears, fused animal ears, bad animal ears, poorly drawn animal ears, extra animal ears, liquid animal ears, heavy animal ears, missing animal ears, text, ui, error, missing fingers, missing limb, fused fingers, one hand with more than 5 fingers, one hand with less than 5 fingers, one hand with more than 5 digit, one hand with less than 5 digit, extra digit, fewer digits, fused digit, missing digit, bad digit, liquid digit, colorful tongue, black tongue, cropped, watermark, username, blurry, JPEG artifacts, signature, 3D, 3D game, 3D game scene, 3D character, malformed feet, extra feet, bad feet, poorly drawn feet, fused feet, missing feet, extra shoes, bad shoes, fused shoes, more than two shoes, poorly drawn shoes, bad gloves, poorly drawn gloves, fused gloves, bad cum, poorly drawn cum, fused cum, bad hairs, poorly drawn hairs, fused hairs, big muscles, ugly, bad face, fused face, poorly drawn face, cloned face, big face, long face, bad eyes, fused eyes poorly drawn eyes, extra eyes, malformed limbs, more than 2 nipples, missing nipples, different nipples, fused nipples, bad nipples, poorly drawn nipples, black nipples, colorful nipples, gross proportions. short arm, (((missing arms))), missing thighs, missing calf, missing legs, mutation, duplicate, morbid, mutilated, poorly drawn hands, more than 1 left hand, more than 1 right hand, deformed, (blurry), disfigured, missing legs, extra arms, extra thighs, more than 2 thighs, extra calf, fused calf, extra legs, bad knee, extra knee, more than 2 legs, bad tails, bad mouth, fused mouth, poorly drawn mouth, bad tongue, tongue within mouth, too long tongue, black tongue, big mouth, cracked mouth, bad mouth, dirty face, dirty teeth, dirty pantie, fused pantie, poorly drawn pantie, fused cloth, poorly drawn cloth, bad pantie, yellow teeth, thick lips, bad cameltoe, colorful cameltoe, bad asshole, poorly drawn asshole, fused asshole, missing asshole, bad anus, bad pussy, bad crotch, bad crotch seam, fused anus, fused pussy, fused anus, fused crotch, poorly drawn crotch, fused seam, poorly drawn anus, poorly drawn pussy, poorly drawn crotch, poorly drawn crotch seam, bad thigh gap, missing thigh gap, fused thigh gap, liquid thigh gap, poorly drawn thigh gap, poorly drawn anus, bad collarbone, fused collarbone, missing collarbone, liquid collarbone, strong girl, obesity, worst quality, low quality, normal quality, liquid tentacles, bad tentacles, poorly drawn tentacles, split tentacles, fused tentacles, missing clit, bad clit, fused clit, colorful clit, black clit, liquid clit, QR code, bar code, censored, safety panties, safety knickers, beard, furry ,pony, pubic hair, mosaic, excrement, faeces, shit, futa, testis

**Comment by shigma** [comment]
有其他人复现此问题吗……我在本地没有复现成功。

**Comment by pansx** [comment]
今天再次出现了这个问题,发现log里出现了这样的报错,但都不是造成卡死时产生的...
app SqliteError: UNIQUE constraint failed: stats_daily.time
                            at SQLiteDriver.#exec (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:269:48)
                            at SQLiteDriver.#create (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:291:48)
                            at SQLiteDriver.upsert (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:256:51)
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async DatabaseService.upsert (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@minatojs\core\lib\index.cjs:529:5)
                            at async _StatisticsProvider._uploadDaily (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@koishijs\plugin-status\lib\index.js:378:5)
                            at async Promise.all (index 0)
                            at async _StatisticsProvider.upload (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@koishijs\plugin-status\lib\index.js:427:7)
2022-10-22 00:17:20 [E] novelai TypeError: res.data.slice is not a function
                            at C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\koishi-plugin-novelai\lib\index.js:338:29
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async _Command.<anonymous> (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\koishi-plugin-novelai\lib\index.js:343:26)
                            at async Array.<anonymous> (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1206:14)
                            at async _Command.execute (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1221:22)
                            at async C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1761:22
                            at async Session2.withScope (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1645:14)
                            at async next (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:970:16)
                            at async next (C:\Users\pansx\AppData\Roaming\Il Harper\Koishi\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:970:16)

**Comment by MaikoTan** [comment]
Looks like the problem is that the `res.data` is neither a string nor `undefined` or `null`?

看起来问题在于`res.data`既不是字符串也不是`undefined`或`null`？

**Comment by shigma** [comment]
用的是 nai 官网吗？

**Comment by LYAN0526** [comment]
有另一个用户也报告了该问题，看起来似乎问题的一致点是都是在onebot上出的
（因为discord没法复现）

**Comment by ilharp** [comment]
根据群友反馈，该问题疑似合并转发超长消息导致风控，Koishi 卡死原因仍未知

Temporary workaround: 插件配置项 `output` 改为「只发送图片」

**Comment by shigma** [comment]
此问题已于 Koishi 4.10.3 修复。
